### ISSUE TITLE
Can not pass the inventory event

### ISSUE THREAD

**Issue by HopeGK** [Sfiguz7/TranscEndence#15]
## Description (Required)
When a player right click the block.in.world_the_end, nothing happens.

## Steps to reproduce the Issue (Required)
![Screenshot_20210218_135438_com microsoft rdc android](https://user-images.githubusercontent.com/63684842/108313963-1b5d7280-71f4-11eb-9b1a-b7df872113f0.jpg)

## Expected behavior (Required)
fix it.

## Server Log / Error Report
[paste.ubuntu.com/p/6nwGPZ6SVn](paste.ubuntu.com/p/6nwGPZ6SVn) 

## Environment (Required)
openjdk8

 - Minecraft Version:1.16.1(paperspigot-138)
 - CS-CoreLib Version:1.7
 - Slimefun Version:4.9
 - Plugin Version: dev22(git7660c)

**Comment by Azakaturan** [comment]
Having the same thing happen on my server:
![image](https://user-images.githubusercontent.com/79327162/108533733-29f86800-728e-11eb-9caf-227c616850e9.png)

![image](https://user-images.githubusercontent.com/79327162/108533781-367cc080-728e-11eb-800d-32dc929e7d15.png)

**Comment by Alessio-Colombo** [comment]
As you may know I’ve been busy with University for the past month and a half, I will be done this Sunday though! Should be a quick fix but I’d like to test it before pushing and I can’t do so before Sunday, sorry for the delay :/ Keep an eye out for new notifications on this post for when the fix will be out!
