### ISSUE TITLE
QUIRP_OSCILLATOR caused an Error / SlimeFun class deprecation

### ISSUE THREAD

**Issue by R4z0rX** [Sfiguz7/TranscEndence#17]
Hi!

So, the deprecation of [SlimeFun class](https://github.com/Slimefun/Slimefun4/commit/ced3cf9f506929e45d935f6492b74a6be6f75ada#diff-ddc9149782ef90d1e08e32cba9863795f62bebc0d53aeac50e160771b058e53e) in [dev build #892](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/#892) broke TranscEndence:
```
22.05 17:50:31 [Server] ERROR [TranscEndence] Item "QUIRP_OSCILLATOR" from TranscEndence vDEV - 33 (git e9b4de1a) has caused an Error!
22.05 17:50:31 [Server] ERROR [TranscEndence] You can report it here: https://github.com/Sfiguz7/TranscEndence/issues
22.05 17:50:31 [Server] ERROR [TranscEndence] An Exception was caught while trying to open the Inventory
22.05 17:50:31 [Server] INFO java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/api/Slimefun
22.05 17:50:31 [Server] INFO at me.sfiguz7.transcendence.implementation.utils.interfaces.TEInventoryBlock$1.canOpen(TEInventoryBlock.java:32) ~[?:?]
22.05 17:50:31 [Server] INFO at me.mrCookieSlime.Slimefun.api.inventory.DirtyChestMenu.canOpen(DirtyChestMenu.java:61) ~[?:?]
22.05 17:50:31 [Server] INFO at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.openInventory(SlimefunItemInteractListener.java:152) ~[?:?]
22.05 17:50:31 [Server] INFO at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.rightClickBlock(SlimefunItemInteractListener.java:126) ~[?:?]
22.05 17:50:31 [Server] INFO at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:70) ~[?:?]
...
```

May I suggest [this fix](https://github.com/Slimefun/Slimefun4/commit/ced3cf9f506929e45d935f6492b74a6be6f75ada#diff-b2e4ffc40193d488425e163e2ee6c76411cb169156c23bca11cb0acb07464f18)?

Thanks in advance!

**Comment by Alessio-Colombo** [comment]
Ah yes of course, I've just fixed the same exact thing in ExtraTools a couple days ago but somehow it hadn't dawned on me that TranscEndence would need the same. I will fix it in about 13h as I'm not home until then

Also thank you for doing the research - this time it wasn't needed but it could've saved a good bit of time in some other cases and is handy to have in any issue report :)

**Comment by R4z0rX** [comment]
Awesome! Don't worry, there's no rush.
Thanks for your kind words, I appreciate it. :)
