### ISSUE TITLE
Transcendence potion effects obtained from Daxis get overridden by beacon effects

### ISSUE THREAD

**Issue by NCBPFluffyBear** [Sfiguz7/TranscEndence#6]
## Description (Required)
When a Daxi is consumed and the player obtains another potion effect of the same kind from a beacon, it overrides the Daxi's effect and it does not get reapplied after the player is out of the beacon's range.

## Steps to reproduce the Issue (Required)
1. Consume a Daxi (R) (Regeneration is the easiest to reproduce this with)
2. Build a beacon and enable regeneration
3. Allow regeneration from the beacon to override the Daxi's regeneration effect

## Expected behavior (Required)
The beacon's effect should be prevented from overriding the Daxi's effect, or the Daxi's effect should be reapplied when the player is no longer in the beacon's range. I noticed that once a Daxi has been consumed that life, another one of the same kind can not be consumed (I'm trying to say that this info is stored). A possible solution would to have Daxis operate like some custom enchant plugins, where the enchant is applied if the player meets certain criteria, like the lore on armor for custom enchant plugins and the stored consumed Daxi data for this addon.

## Server Log / Error Report
No Errors

## Environment (Required)
Minecraft: 1.15.2
Slimefun: DEV 560 (git b138b)
CS-CoreLib: DEV 88 (git 6a39a)
TranscEndence: DEV 11 (git f5d03)

**Comment by Alessio-Colombo** [comment]
For clarification (and future reference), beacons do not override potion effects from TE since they are lower level. The issue arises with custom enchants and WorldGuard regions. Working on a fix

**Comment by Alessio-Colombo** [comment]
As I have not found a way to stop CE to do their dumb stuff I am forced to close this (after a long time). If it ever becomes an issue for others I will try to get in touch with its Dev and see if anything can be done to add support but being pretty small of a plugin it's probably going to be more effort than they deem worth - who knows one might always try.
Sorry Fluffy but for now you'll have to make do :(
