### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 100petr** [Sfiguz7/TranscEndence#7]
## Description (Required)
When trying to do NanoBotCrafter it give error

## Steps to reproduce the Issue (Required)
try to craft NanoBotCrafter

## Expected behavior (Required)
NanoBotCrafter will be crafted

## Server Log / Error Report:
https://pastebin.com/68VBfRRn

## Environment (Required)
![Screenshot_20200718-082132_Samsung Internet](https://user-images.githubusercontent.com/29830635/87846414-e260c680-c8cf-11ea-83c7-c77afa64884b.jpg)
![Screenshot_20200718-082202_Samsung Internet](https://user-images.githubusercontent.com/29830635/87846419-eee51f00-c8cf-11ea-84b4-c512c3ae9c91.jpg)

**Comment by Alessio-Colombo** [comment]
You’re... Crafting it? It is a Multiblock structure like the Enhanced Crafting Table, you just have to place down the blocks

**Comment by 100petr** [comment]
I wrote bullshit. I didn't try it, I just wanted to write something about it.

**Comment by 100petr** [comment]
So I have to ignore the error?

**Comment by Alessio-Colombo** [comment]
Hadn’t checked the pastebin link, it seems like something I have to fix. From your comment I thought this was invalid since you said “I wrote bullshit, I didn’t try it”. I’ll look into this next week as I’m away until Sunday

**Comment by 100petr** [comment]
I wrote bullshit because I don't have access to a computer right now, so I can't get into the game and I only see what's going on through the console.

**Comment by Alessio-Colombo** [comment]
I cannot reproduce the error. What are you doing to do with it? Are you crafting something?
